### ISSUE TITLE
Question: What differ cellauto from terra?

### ISSUE THREAD

**Issue by luckylooke** [sanojian/cellauto#2]
At first glance, they look similar to each other, but you must have motivation for cellauto. Thanks ;)

**Comment by sanojian** [comment]
At first glance, they are very similar since the APIs are similar.  Under the hood, they share no code.  Terra relies heavily on a custom version of underscore and cellauto.js does not need any third party code.  I also wrote it with performance in mind since I wanted to make some more complex examples and I found Terra emphasized ease of use over performance.  Terra is more mature and allows you to create creatures for example, which cellauto does not support yet.
